/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MarketIntelligenceRouteImport } from './routes/market-intelligence'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as SupportRouteImport } from './routes/support'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppCommissionsRouteImport } from './routes/app.commissions'
import { Route as AppIntelligenceRouteImport } from './routes/app.intelligence'
import { Route as AppLeadsRouteImport } from './routes/app.leads'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppOpportunitiesRouteImport } from './routes/app.opportunities'
import { Route as AppProjectsRouteImport } from './routes/app.projects'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppTasksRouteImport } from './routes/app.tasks'
import { Route as AppTeamRouteImport } from './routes/app.team'
import { Route as AppVisitsRouteImport } from './routes/app.visits'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketIntelligenceRoute = MarketIntelligenceRouteImport.update({
  id: '/market-intelligence',
  path: '/market-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCommissionsRoute = AppCommissionsRouteImport.update({
  id: '/app/commissions',
  path: '/app/commissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIntelligenceRoute = AppIntelligenceRouteImport.update({
  id: '/app/intelligence',
  path: '/app/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/app/leads',
  path: '/app/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/app/notifications',
  path: '/app/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOpportunitiesRoute = AppOpportunitiesRouteImport.update({
  id: '/app/opportunities',
  path: '/app/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/app/projects',
  path: '/app/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/app/settings',
  path: '/app/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/app/tasks',
  path: '/app/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/app/team',
  path: '/app/team',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVisitsRoute = AppVisitsRouteImport.update({
  id: '/app/visits',
  path: '/app/visits',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/market-intelligence': typeof MarketIntelligenceRoute
  '/register': typeof RegisterRoute
  '/solutions': typeof SolutionsRoute
  '/support': typeof SupportRoute
  '/app/commissions': typeof AppCommissionsRoute
  '/app/intelligence': typeof AppIntelligenceRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/opportunities': typeof AppOpportunitiesRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/team': typeof AppTeamRoute
  '/app/visits': typeof AppVisitsRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/app/': typeof AppIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/market-intelligence': typeof MarketIntelligenceRoute
  '/register': typeof RegisterRoute
  '/solutions': typeof SolutionsRoute
  '/support': typeof SupportRoute
  '/app/commissions': typeof AppCommissionsRoute
  '/app/intelligence': typeof AppIntelligenceRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/opportunities': typeof AppOpportunitiesRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/team': typeof AppTeamRoute
  '/app/visits': typeof AppVisitsRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/app': typeof AppIndexRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/market-intelligence': typeof MarketIntelligenceRoute
  '/register': typeof RegisterRoute
  '/solutions': typeof SolutionsRoute
  '/support': typeof SupportRoute
  '/app/commissions': typeof AppCommissionsRoute
  '/app/intelligence': typeof AppIntelligenceRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/opportunities': typeof AppOpportunitiesRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/team': typeof AppTeamRoute
  '/app/visits': typeof AppVisitsRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/app/': typeof AppIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/market-intelligence'
    | '/register'
    | '/solutions'
    | '/support'
    | '/app/commissions'
    | '/app/intelligence'
    | '/app/leads'
    | '/app/notifications'
    | '/app/opportunities'
    | '/app/projects'
    | '/app/settings'
    | '/app/tasks'
    | '/app/team'
    | '/app/visits'
    | '/projects/$slug'
    | '/app/'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/market-intelligence'
    | '/register'
    | '/solutions'
    | '/support'
    | '/app/commissions'
    | '/app/intelligence'
    | '/app/leads'
    | '/app/notifications'
    | '/app/opportunities'
    | '/app/projects'
    | '/app/settings'
    | '/app/tasks'
    | '/app/team'
    | '/app/visits'
    | '/projects/$slug'
    | '/app'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/login'
    | '/market-intelligence'
    | '/register'
    | '/solutions'
    | '/support'
    | '/app/commissions'
    | '/app/intelligence'
    | '/app/leads'
    | '/app/notifications'
    | '/app/opportunities'
    | '/app/projects'
    | '/app/settings'
    | '/app/tasks'
    | '/app/team'
    | '/app/visits'
    | '/projects/$slug'
    | '/app/'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  MarketIntelligenceRoute: typeof MarketIntelligenceRoute
  RegisterRoute: typeof RegisterRoute
  SolutionsRoute: typeof SolutionsRoute
  SupportRoute: typeof SupportRoute
  AppCommissionsRoute: typeof AppCommissionsRoute
  AppIntelligenceRoute: typeof AppIntelligenceRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOpportunitiesRoute: typeof AppOpportunitiesRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTasksRoute: typeof AppTasksRoute
  AppTeamRoute: typeof AppTeamRoute
  AppVisitsRoute: typeof AppVisitsRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  AppIndexRoute: typeof AppIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market-intelligence': {
      id: '/market-intelligence'
      path: '/market-intelligence'
      fullPath: '/market-intelligence'
      preLoaderRoute: typeof MarketIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/commissions': {
      id: '/app/commissions'
      path: '/app/commissions'
      fullPath: '/app/commissions'
      preLoaderRoute: typeof AppCommissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/intelligence': {
      id: '/app/intelligence'
      path: '/app/intelligence'
      fullPath: '/app/intelligence'
      preLoaderRoute: typeof AppIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/leads': {
      id: '/app/leads'
      path: '/app/leads'
      fullPath: '/app/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/app/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/opportunities': {
      id: '/app/opportunities'
      path: '/app/opportunities'
      fullPath: '/app/opportunities'
      preLoaderRoute: typeof AppOpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/projects': {
      id: '/app/projects'
      path: '/app/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/tasks': {
      id: '/app/tasks'
      path: '/app/tasks'
      fullPath: '/app/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/team': {
      id: '/app/team'
      path: '/app/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/visits': {
      id: '/app/visits'
      path: '/app/visits'
      fullPath: '/app/visits'
      preLoaderRoute: typeof AppVisitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  MarketIntelligenceRoute: MarketIntelligenceRoute,
  RegisterRoute: RegisterRoute,
  SolutionsRoute: SolutionsRoute,
  SupportRoute: SupportRoute,
  AppCommissionsRoute: AppCommissionsRoute,
  AppIntelligenceRoute: AppIntelligenceRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOpportunitiesRoute: AppOpportunitiesRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTasksRoute: AppTasksRoute,
  AppTeamRoute: AppTeamRoute,
  AppVisitsRoute: AppVisitsRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  AppIndexRoute: AppIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
